User can see the filters applied to the datasets
TheMinefreak23/fair-rec-kit-app pull request #126
Opened 2022-05-30 15:40 UTC by aleks-24

todo: user can see filters applied to results

2022-05-30 16:59 UTC, lanlegion commented
it's alright

2022-05-30 17:01 UTC, lanlegion requested changes
RIP single quotes T_T fix your formatter

2022-05-31 07:49 UTC, aleks-24 commented
> RIP single quotes T_T fix your formatter

oops

2022-06-01 05:40 UTC, lanlegion approved these changes
go o   d

2022-06-01 05:40 UTC, merged